version: "3.8"

services:
  streamlit-app:
    image: ivo196/stremlit-chat-gemini:latest
    container_name: streamlit-chat-gemini
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - GEMINI_API=${GEMINI_API}
