apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: chat
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      nodePort: 30001
